export interface FederationInfo {
    id: string;
    shortName: string;
    fullName: string;
    affiliate?: string;
}

export interface RuleCategory {
    id: string;
    label: string;
    description?: string;
}

export const FEDERATIONS: FederationInfo[] = [
    { id: 'usapl', shortName: 'USAPL', fullName: 'USA Powerlifting (USAPL)' },
    { id: 'pa', shortName: 'PA', fullName: 'Powerlifting America (PA)', affiliate: '*IPF Affiliate' },
    { id: 'uspa', shortName: 'USPA', fullName: 'United States Powerlifting Association (USPA)' },
    { id: 'plu', shortName: 'PLU', fullName: 'Powerlifting United (PLU)' },
    { id: 'wrpf', shortName: 'WRPF', fullName: 'World Raw Powerlifting Federation (WRPF)' },
    { id: 'rps', shortName: 'RPS', fullName: 'Revolution Powerlifting Syndicate (RPS)' },
    { id: 'apf', shortName: 'APF', fullName: 'American Powerlifting Federation (APF)', affiliate: '*WPC affiliate' },
    { id: 'ipa', shortName: 'IPA', fullName: 'International Powerlifting Association (IPA)' },
    { id: 'upa', shortName: 'UPA', fullName: 'United Powerlifting Association (UPA)' },
];

export const RULE_CATEGORIES: RuleCategory[] = [
    { id: 'membership_cost', label: 'Adult membership cost' },
    { id: 'weigh_ins', label: 'Weigh ins' },
    { id: 'approved_equipment', label: 'Approved equipment list' },
    { id: 'drug_testing', label: 'Drug testing' },
    { id: 'mono_lift', label: 'Mono lift allowed' },
    { id: 'combo_rack', label: 'Combo rack' },
    { id: 'deadlift_bar', label: 'Deadlift bar' },
    { id: 'power_bar', label: 'Power bar' },
    { id: 'squat_bar', label: 'Squat bar' },
    { id: 'heels_flat_bench', label: 'Heels flat during bench press' },
    { id: 'thumbless_grip_bench', label: 'Thumbless/reverse grip during bench' },
    { id: 'head_flat_bench', label: 'Head flat during bench' },
    { id: 'feet_on_bench_setup', label: 'Feet allowed on bench during set up' },
    { id: 'knee_wraps', label: 'Knee wraps' },
    { id: 'talon_grip_squats', label: 'Talon grip on squats' },
    { id: 'trans_lifters', label: 'Trans lifters' },
    { id: 'tshirt_deadlifts', label: 'T-shirt for deads' },
    { id: 'other_feds_allowed', label: 'Membership in other feds allowed' },
];

export const FEDERATION_RULES_MATRIX: Record<string, Record<string, string>> = {
    membership_cost: {
        usapl: '$75',
        pa: '$75',
        uspa: '$80',
        plu: '$65',
        wrpf: '??',
        rps: '$0',
        apf: '$30',
        ipa: '$50',
        upa: '$40',
    },
    weigh_ins: {
        usapl: '2 hr',
        pa: '2 hr',
        uspa: '24 hr',
        plu: '24 hr',
        wrpf: '24 hr',
        rps: '24 hr',
        apf: '24 hr',
        ipa: '24 hr',
        upa: '24 hr',
    },
    approved_equipment: {
        usapl: 'No',
        pa: 'Yes',
        uspa: 'Yes',
        plu: 'No',
        wrpf: 'No',
        rps: 'No',
        apf: 'No',
        ipa: 'No',
        upa: 'No',
    },
    drug_testing: {
        usapl: 'Yes',
        pa: 'Yes',
        uspa: 'DT division',
        plu: 'DT division',
        wrpf: 'DT division',
        rps: 'Amateur division',
        apf: 'Amateur division',
        ipa: 'Amateur division',
        upa: 'Amateur division',
    },
    mono_lift: {
        usapl: 'No',
        pa: 'No',
        uspa: 'No',
        plu: 'Yes',
        wrpf: 'Yes (depends on meet director)',
        rps: 'Yes, required for state level meets and higher',
        apf: 'Required',
        ipa: 'Required',
        upa: 'Yes',
    },
    combo_rack: {
        usapl: 'Yes',
        pa: 'Yes',
        uspa: 'Yes',
        plu: 'Yes',
        wrpf: 'Yes',
        rps: 'Yes',
        apf: 'Bench only',
        ipa: 'Bench only',
        upa: 'Bench only, can be used in raw only competitions for squat',
    },
    deadlift_bar: {
        usapl: 'No',
        pa: 'No',
        uspa: 'Yes',
        plu: 'Yes',
        wrpf: 'Yes',
        rps: 'Allowed, not required',
        apf: 'Yes',
        ipa: 'Yes',
        upa: 'Yes',
    },
    power_bar: {
        usapl: 'Yes, all three lifts',
        pa: 'Yes, all three lifts',
        uspa: 'Bench press only',
        plu: 'Bench press only',
        wrpf: 'Bench press only',
        rps: 'Yes, 25kg bench bar also allowed',
        apf: 'Yes, 25kg bench bar also allowed',
        ipa: 'Yes, 25kg bench bar also allowed',
        upa: 'Bench press only',
    },
    squat_bar: {
        usapl: 'No',
        pa: 'No',
        uspa: 'Yes',
        plu: 'Yes',
        wrpf: 'Yes',
        rps: 'Allowed, not required',
        apf: 'Yes, 30kg squat bar also allowed',
        ipa: 'Yes',
        upa: 'Yes',
    },
    heels_flat_bench: {
        usapl: 'Required',
        pa: 'Required',
        uspa: 'Not required',
        plu: 'Not required',
        wrpf: 'Not required',
        rps: 'Not required',
        apf: 'Not required',
        ipa: 'Not required',
        upa: 'Not required',
    },
    thumbless_grip_bench: {
        usapl: 'Not permitted',
        pa: 'Not permitted',
        uspa: 'Permitted',
        plu: 'Permitted',
        wrpf: 'Permitted',
        rps: 'Permitted',
        apf: 'Permitted',
        ipa: 'Permitted',
        upa: 'Permitted',
    },
    head_flat_bench: {
        usapl: 'Not required',
        pa: 'Required',
        uspa: 'Not required',
        plu: 'Not required',
        wrpf: 'Not required',
        rps: 'Not required',
        apf: 'Not required',
        ipa: 'Not required',
        upa: 'Not required',
    },
    feet_on_bench_setup: {
        usapl: 'Permitted',
        pa: 'Not permitted',
        uspa: 'Permitted',
        plu: 'Permitted',
        wrpf: 'Permitted',
        rps: 'Permitted',
        apf: 'Permitted',
        ipa: 'Permitted',
        upa: 'Permitted',
    },
    knee_wraps: {
        usapl: '2m',
        pa: '2m',
        uspa: '2.5m',
        plu: '2.5m',
        wrpf: '2.5m',
        rps: '3m',
        apf: '3m',
        ipa: '3m',
        upa: '3m',
    },
    talon_grip_squats: {
        usapl: 'Not permitted',
        pa: 'No mention',
        uspa: 'No mention',
        plu: 'Permitted',
        wrpf: 'No mention',
        rps: 'No mention',
        apf: 'No mention',
        ipa: 'No mention',
        upa: 'No mention',
    },
    trans_lifters: {
        usapl: 'Separate category',
        pa: 'Yes',
        uspa: 'Untested division only',
        plu: 'Yes',
        wrpf: 'No mention',
        rps: 'Yes, see rule book',
        apf: 'No mention',
        ipa: 'No mention',
        upa: 'No mention',
    },
    tshirt_deadlifts: {
        usapl: 'Not required',
        pa: 'Required',
        uspa: 'Not required',
        plu: 'Not required',
        wrpf: 'Not required',
        rps: 'Not required',
        apf: 'Not required',
        ipa: 'Not required',
        upa: "Meet director's discretion",
    },
    other_feds_allowed: {
        usapl: 'Permitted',
        pa: 'Not permitted',
        uspa: 'Permitted',
        plu: 'Permitted',
        wrpf: 'Permitted',
        rps: 'Permitted',
        apf: 'Permitted',
        ipa: 'Permitted',
        upa: 'Permitted',
    },
};
